services:
  # Frontend - Next.js application
  - type: web
    name: onboarding-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://onboarding-backend.onrender.com/api
    autoDeploy: true

  # Backend - Express API
  - type: web
    name: onboarding-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: onboarding-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://onboarding-frontend.onrender.com
    autoDeploy: true

databases:
  - name: onboarding-db
    plan: free 